import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'..');
const out=path.join(root,'docs');fs.mkdirSync(out,{recursive:true});
for(const name of ['index.html','app.js','device.js','shared.js','style.css','bird.png','share-music-library.png'])fs.copyFileSync(path.join(root,'public',name),path.join(out,name));
let app=fs.readFileSync(path.join(out,'app.js'),'utf8');
app="import {cloudRequest,route,pageLink} from './cloud.js?v=kids-20260917';\n"+app;
app=app.replaceAll('location.pathname','route');
const start=app.indexOf('async function request('),end=app.indexOf('\nfunction activeSongs',start);
app=app.slice(0,start)+'const request=cloudRequest;'+app.slice(end);
app=app.replace("function classLink(){return location.origin+'/listen'}","function classLink(){return new URL(pageLink('/listen'),location.href).href}");
app=app.replaceAll("location.href='/teacher'","location.href=pageLink('/teacher')");
app=app.replace("window.open(isDemo?'/demo/tablet':'/listen','_blank','noopener')","window.open(pageLink(isDemo?'/demo/tablet':'/listen'),'_blank','noopener')");
app=app.replace("history.replaceState(null,'',route)","history.replaceState(null,'',pageLink(route))");
app=app.replaceAll('href="/teacher"','href="?page=teacher"').replaceAll('href="/demo?view=teacher"','href="?page=demo&view=teacher"');
fs.writeFileSync(path.join(out,'app.js'),app);
fs.writeFileSync(path.join(out,'index.html'),fs.readFileSync(path.join(out,'index.html'),'utf8').replace('href="/style.css"','href="./style.css?v=kids-20260917"').replace('src="/app.js"','src="./app.js?v=kids-20260917"').replace('<meta charset="utf-8">','<meta charset="utf-8"><meta name="referrer" content="no-referrer">'));
fs.writeFileSync(path.join(out,'shared.js'),fs.readFileSync(path.join(out,'shared.js'),'utf8').replace("cover:'/bird.png'","cover:'./bird.png'"));
fs.copyFileSync(path.join(root,'cloud','client.js'),path.join(out,'cloud.js'));
fs.writeFileSync(path.join(out,'.nojekyll'),'');
fs.writeFileSync(path.join(root,'cloud','schema.mjs'),'export const schema='+JSON.stringify(fs.readFileSync(path.join(root,'cloud','schema.sql'),'utf8'))+';\n');
