import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import path from 'node:path';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
const project=path.resolve(import.meta.dirname,'..');
const pg=new PGlite();
await pg.exec("CREATE ROLE anon; CREATE ROLE authenticated; CREATE SCHEMA storage; CREATE TABLE storage.buckets(id text PRIMARY KEY,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);");
function wrap(cx){const sql=async(strings,...args)=>{if(strings.join('').includes('pg_advisory'))return [];return (await cx.query(strings.join('?'),args)).rows};sql.unsafe=(s,args=[])=>{const task=async()=>s.includes('pg_advisory')?[]:(await cx.query(s,args)).rows;return {then:(a,b)=>task().then(a,b),simple:()=>cx.exec(s)}};sql.begin=fn=>pg.transaction(tx=>fn(wrap(tx)));return sql}
globalThis.__qaPostgres=()=>wrap(pg);
globalThis.Deno={env:{get:key=>({SUPABASE_URL:'https://test.invalid',SUPABASE_SERVICE_ROLE_KEY:'test-service-only',SUPABASE_DB_URL:'test-db'})[key]}};
const files=new Map();globalThis.fetch=async(url,o={})=>{assert.equal(o.headers.Authorization,'Bearer test-service-only');const file=decodeURIComponent(new URL(url).pathname.split('/').pop());if(url.includes('/object/sign/')){assert.ok(files.has(file));return Response.json({signedURL:'/object/sign/music-media/'+file+'?token=test'})}if(o.method==='DELETE'){for(const name of JSON.parse(o.body).prefixes)files.delete(name);return Response.json({})}if(o.method==='POST'){files.set(file,o.body);return Response.json({})}throw new Error('Unexpected storage operation')};
let source=fs.readFileSync(path.join(project,'cloud/edge.mjs'),'utf8').replace("import postgres from 'npm:postgres@3.4.7';","const postgres=globalThis.__qaPostgres;").replace("'../public/shared.js'",JSON.stringify(pathToFileURL(path.join(project,'public/shared.js')).href)).replace("'./schema.mjs'",JSON.stringify(pathToFileURL(path.join(project,'cloud/schema.mjs')).href));
const {handler}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const origin='https://edupoplab.github.io';
async function call(p,method='GET',body={},jar={},originValue=origin){const headers={Origin:originValue};for(const [k,v] of Object.entries(jar))if(v)headers['x-music-'+k]=v;let payload=body;if(!(body instanceof FormData)){headers['Content-Type']='application/json';payload=JSON.stringify({path:p,method,body})}const r=await handler(new Request('https://test.invalid/functions/v1/music-api',{method:'POST',headers,body:payload}));const j=await r.json();for(const [k,v] of Object.entries(j._credentials||{})){if(v)jar[k]=v;else delete jar[k]}return {status:r.status,data:j}}
const staff={},teacher={},tablet={};
assert.equal((await call('/api/status')).status,200);
assert.equal((await call('/api/setup','POST',{name:'Blocked',email:'bad@example.test',password:'not-a-real-password'})).status,400);
const bootstrap='qa-bootstrap-token';await pg.query('INSERT INTO music.bootstrap VALUES($1,$2)',[createHash('sha256').update(bootstrap).digest('hex'),Date.now()+60000]);
assert.equal((await call('/api/setup','POST',{token:bootstrap,name:'Test Admin',email:'admin@example.test',password:'test-admin-password-123'},staff)).status,200);
assert.equal((await call('/api/setup','POST',{token:bootstrap,name:'Blocked',email:'bad@example.test',password:'not-a-real-password'})).status,403);
assert.equal((await call('/api/library')).status,401);
assert.equal((await call('/api/library','GET',{},staff,'https://evil.invalid')).status,403);
const library=(await call('/api/library','GET',{},staff)).data;assert.equal(library.topics.length,20);const [first,second]=library.classes;
const invite=(await call('/api/invitations','POST',{name:'Test Teacher',email:'teacher@example.test',classIds:[first.id]},staff)).data.url.split('#')[1];
assert.equal((await call('/api/accept-invite','POST',{token:invite,password:'test-teacher-password-123'},teacher)).status,200);
assert.equal((await call('/api/accept-invite','POST',{token:invite,password:'test-teacher-password-123'},{})).status,410);
assert.deepEqual((await call('/api/library','GET',{},teacher)).data.classes.map(c=>c.id),[first.id]);
assert.equal((await call('/api/classes/'+second.id+'/publish','POST',{items:[],revision:0},teacher)).status,403);
const form=new FormData();form.set('title','테스트 노래');form.set('tags',JSON.stringify(['봄','식물']));form.set('audio',new Blob(['ID3\0test'],{type:'audio/mpeg'}),'test.mp3');
const added=await call('/api/songs','POST',form,teacher);assert.equal(added.status,200);const sid=added.data.id;
assert.equal((await call('/api/classes/'+first.id+'/draft','POST',{items:[sid],revision:0},teacher)).status,200);
assert.equal((await call('/api/device/enroll','POST',{classId:first.id},teacher)).status,401);
assert.equal((await call('/api/device/auth','POST',{email:'teacher@example.test',password:'test-teacher-password-123'},tablet)).status,200);
assert.equal((await call('/api/device/enroll','POST',{classId:second.id},tablet)).status,403);
assert.equal((await call('/api/device/enroll','POST',{classId:first.id},tablet)).status,200);
assert.equal(tablet.session,undefined);assert.equal(tablet.pairing,undefined);
assert.equal((await call('/api/device/listen','GET',{},tablet)).data.songs.length,0);
assert.equal((await call('/api/classes/'+first.id+'/publish','POST',{items:[sid],revision:0},teacher)).status,409);
assert.equal((await call('/api/classes/'+first.id+'/publish','POST',{items:[sid],revision:1},teacher)).status,200);
assert.equal((await call('/api/device/listen','GET',{},tablet)).data.songs[0].id,sid);
assert.equal((await call('/api/library','GET',{},tablet)).status,401);
assert.equal((await call('/api/device/enroll','POST',{classId:second.id},tablet)).status,401);
const previousSession={...teacher};await call('/api/device/enter','POST',{},teacher);assert.equal((await call('/api/library','GET',{},previousSession)).status,401);
await call('/api/login','POST',{email:'teacher@example.test',password:'test-teacher-password-123'},teacher);
const tid=(await call('/api/library','GET',{},staff)).data.teachers.find(t=>t.role==='teacher').id;
const reset=(await call('/api/teachers/'+tid+'/reset','POST',{},staff)).data.url.split('#')[1];
assert.equal((await call('/api/reset-password','POST',{token:reset,password:'replacement-test-password'},{})).status,200);
assert.equal((await call('/api/library','GET',{},teacher)).status,401);
assert.equal((await call('/api/reset-password','POST',{token:reset,password:'replacement-test-password'},{})).status,410);
const permissions=await pg.query("SELECT has_schema_privilege('anon','music','USAGE') AS allowed");assert.equal(permissions.rows[0].allowed,false);
console.log('PASS: cloud bootstrap, role isolation, one-use invitations, uploads, draft/publish, conflict checks, device enrollment, session revocation, password reset and private schema');
await pg.close();

