import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {randomBytes,createHash,scryptSync,timingSafeEqual} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {TOPICS} from './public/shared.js';
const root=path.dirname(fileURLToPath(import.meta.url));
const host=process.env.HOST||'127.0.0.1',port=Number(process.env.PORT||4317);
const origin=process.env.APP_ORIGIN||`http://${host}:${port}`;
const dataDir=process.env.DATA_DIR||path.join(root,'data');
fs.mkdirSync(path.join(dataDir,'media'),{recursive:true});
const db=new DatabaseSync(path.join(dataDir,'library.sqlite'));
db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password TEXT NOT NULL,role TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS classes(id TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL,token TEXT UNIQUE NOT NULL,draft TEXT NOT NULL DEFAULT '[]',published TEXT NOT NULL DEFAULT '[]',revision INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS assignments(user_id TEXT REFERENCES users(id),class_id TEXT REFERENCES classes(id),PRIMARY KEY(user_id,class_id));
CREATE TABLE IF NOT EXISTS devices(token TEXT PRIMARY KEY,class_id TEXT NOT NULL REFERENCES classes(id),created_by TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS device_pairings(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS topics(name TEXT PRIMARY KEY);
CREATE TABLE IF NOT EXISTS songs(id TEXT PRIMARY KEY,title TEXT NOT NULL,tags TEXT NOT NULL,audio_file TEXT,cover_file TEXT,cover_type TEXT,emoji TEXT NOT NULL,color TEXT NOT NULL,sample INTEGER NOT NULL DEFAULT 0,archived INTEGER NOT NULL DEFAULT 0,created_by TEXT REFERENCES users(id),created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS invitations(id TEXT PRIMARY KEY,email TEXT NOT NULL,name TEXT NOT NULL,token TEXT UNIQUE NOT NULL,class_ids TEXT NOT NULL,expires INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS password_resets(token TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),expires INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS collections(id TEXT PRIMARY KEY,class_id TEXT REFERENCES classes(id),name TEXT NOT NULL,items TEXT NOT NULL);
`);
function transaction(fn){db.exec('BEGIN IMMEDIATE');try{const r=fn();db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}
transaction(()=>{for(const t of TOPICS)db.prepare('INSERT OR IGNORE INTO topics(name) VALUES(?)').run(t)});
const q=(sql,...args)=>db.prepare(sql).all(...args),one=(sql,...args)=>db.prepare(sql).get(...args),run=(sql,...args)=>db.prepare(sql).run(...args);
const id=()=>randomBytes(16).toString('hex'),token=()=>randomBytes(32).toString('base64url'),hash=s=>createHash('sha256').update(s).digest('hex');
const fail=(status,message)=>{const e=new Error(message);e.status=status;throw e};
const json=(res,status,value)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(value))};
function text(v,max=100){if(typeof v!=='string'||!v.trim()||v.trim().length>max)fail(400,'입력 내용을 확인해 주세요.');return v.trim()}
function email(v){const e=text(v,254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))fail(400,'이메일 주소를 확인해 주세요.');return e}
function password(v){if(typeof v!=='string'||v.length<12||v.length>128)fail(400,'비밀번호는 12~128자로 입력해 주세요.');const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(v,salt,64).toString('hex')}`}
function matches(v,stored){if(typeof v!=='string'||v.length>128)return false;const [salt,key]=stored.split(':');return timingSafeEqual(scryptSync(v,salt,64),Buffer.from(key,'hex'))}
function session(req){const raw=(req.headers.cookie||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('music_session='))?.split('=')[1];if(!raw)return null;return one('SELECT u.id,u.email,u.name,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>? AND u.active=1',hash(raw),Date.now())||null}
function requireUser(req){const u=session(req);if(!u)fail(401,'로그인이 필요합니다.');return u}
function admin(req){const u=requireUser(req);if(u.role!=='admin')fail(403,'관리자만 이용할 수 있습니다.');return u}
function canClass(u,cid){if(!one('SELECT id FROM classes WHERE id=?',cid))fail(404,'반을 찾을 수 없습니다.');if(u.role!=='admin'&&!one('SELECT user_id FROM assignments WHERE user_id=? AND class_id=?',u.id,cid))fail(403,'담당 반만 관리할 수 있습니다.')}
async function body(req,max=100000){let size=0,parts=[];for await(const b of req){size+=b.length;if(size>max)fail(413,'파일이 너무 큽니다. MP3는 25MB, 그림은 4MB까지 올릴 수 있습니다.');parts.push(b)}return Buffer.concat(parts)}
async function parse(req){try{return JSON.parse((await body(req)).toString())}catch(e){if(e.status)throw e;fail(400,'요청 형식이 올바르지 않습니다.')}}
function tags(input){if(!Array.isArray(input)||!input.length||input.length>8)fail(400,'주제를 1~8개 선택해 주세요.');const a=[...new Set(input.map(v=>text(v,30)))];for(const t of a)if(!one('SELECT name FROM topics WHERE name=?',t))fail(400,'등록되지 않은 주제입니다.');return a}
function songIds(ids){if(!Array.isArray(ids)||ids.length>500||ids.some(x=>typeof x!=='string'))fail(400,'곡 목록을 확인해 주세요.');const unique=[...new Set(ids)];for(const x of unique)if(!one('SELECT id FROM songs WHERE id=? AND archived=0',x))fail(400,'보관 처리된 곡이 있습니다. 목록을 새로고침해 주세요.');return unique}
function classRow(c){return {...c,draft:JSON.parse(c.draft),published:JSON.parse(c.published)}}
function songRow(s,access=''){return {id:s.id,title:s.title,tags:JSON.parse(s.tags),emoji:s.emoji,color:s.color,sample:!!s.sample,archived:!!s.archived,audio:s.audio_file?`/api/media/${s.id}/audio${access}`:null,cover:s.cover_file?`/api/media/${s.id}/cover${access}`:(s.id==='sample-bird'?'/bird.png':null)}}
const attempts=new Map();function throttle(key){const now=Date.now(),v=attempts.get(key);if(v&&v.until>now&&v.count>=10)fail(429,'시도가 너무 많습니다. 15분 뒤 다시 시도해 주세요.');if(!v||v.until<now)attempts.set(key,{count:1,until:now+900000});else v.count++;if(attempts.size>5000)for(const [k,v]of attempts)if(v.until<now)attempts.delete(k)}
function cookie(res,raw,clear=false){res.appendHeader('Set-Cookie',`music_session=${raw}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${clear?0:43200}${origin.startsWith('https:')?'; Secure':''}`)}
function makeSession(res,u){const t=token();run('DELETE FROM sessions WHERE expires<?',Date.now());run('INSERT INTO sessions VALUES(?,?,?)',hash(t),u.id,Date.now()+43200000);cookie(res,t)}

const DEVICE_LIFETIME=400*86400000;
function readCookie(req,name){return (req.headers.cookie||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(name+'='))?.slice(name.length+1)||''}
function deviceCookie(res,name,value,seconds){res.appendHeader('Set-Cookie',name+'='+value+'; HttpOnly; SameSite=Lax; Path=/; Max-Age='+seconds+(origin.startsWith('https:')?'; Secure':''))}
function endTeacherSession(req,res){const raw=readCookie(req,'music_session');if(raw)run('DELETE FROM sessions WHERE token=?',hash(raw));cookie(res,'',true)}
function getDevice(req){const raw=readCookie(req,'music_device');if(!raw)return null;return one('SELECT c.*,d.token AS device_hash FROM devices d JOIN classes c ON c.id=d.class_id WHERE d.token=? AND d.expires>?',hash(raw),Date.now())||null}
function pairing(req){const raw=readCookie(req,'music_pairing');const u=raw?one('SELECT u.id,u.name,u.role FROM device_pairings p JOIN users u ON u.id=p.user_id WHERE p.token=? AND p.expires>? AND u.active=1',hash(raw),Date.now()):null;if(!u)fail(401,'교사 인증 시간이 지났습니다. 다시 인증해 주세요.');return u}
function clearPairing(req,res){const raw=readCookie(req,'music_pairing');if(raw)run('DELETE FROM device_pairings WHERE token=?',hash(raw));deviceCookie(res,'music_pairing','',0)}
function deviceSongs(c){const rows=q('SELECT * FROM songs WHERE archived=0');return {className:c.name,classId:c.id,revision:c.revision,songs:JSON.parse(c.published).map(id=>rows.find(s=>s.id===id)).filter(Boolean).map(s=>songRow(s,'?device=1'))}}

const setupAllowed=()=>host==='127.0.0.1'&&process.env.NODE_ENV!=='production';
async function api(req,res,url){const p=url.pathname;
if(!['GET','HEAD'].includes(req.method)&&req.headers.origin!==origin)fail(403,'다른 사이트에서 보낸 요청은 허용하지 않습니다.');

if(p==='/api/device/enter'&&req.method==='POST'){endTeacherSession(req,res);clearPairing(req,res);const c=getDevice(req);return json(res,200,{configured:!!c,className:c?.name||null})}
if(p==='/api/device/auth'&&req.method==='POST'){throttle('device-auth:'+req.socket.remoteAddress);const b=await parse(req),u=one('SELECT * FROM users WHERE email=? AND active=1',email(b.email));if(!u||!matches(b.password,u.password))fail(401,'이메일 또는 비밀번호를 확인해 주세요.');attempts.delete('device-auth:'+req.socket.remoteAddress);const classes=(u.role==='admin'?q('SELECT id,name FROM classes'):q('SELECT c.id,c.name FROM classes c JOIN assignments a ON a.class_id=c.id WHERE a.user_id=?',u.id));clearPairing(req,res);endTeacherSession(req,res);const raw=token();run('DELETE FROM device_pairings WHERE expires<?',Date.now());run('INSERT INTO device_pairings VALUES(?,?,?)',hash(raw),u.id,Date.now()+600000);deviceCookie(res,'music_pairing',raw,600);return json(res,200,{name:u.name,classes})}
if(p==='/api/device/enroll'&&req.method==='POST'){const u=pairing(req),b=await parse(req);canClass(u,b.classId);const raw=token();transaction(()=>{const old=readCookie(req,'music_device');if(old)run('DELETE FROM devices WHERE token=?',hash(old));run('INSERT INTO devices VALUES(?,?,?,?)',hash(raw),b.classId,u.id,Date.now()+DEVICE_LIFETIME);clearPairing(req,res);endTeacherSession(req,res)});deviceCookie(res,'music_device',raw,DEVICE_LIFETIME/1000);return json(res,201,{ok:true})}
if(p==='/api/device/cancel'&&req.method==='POST'){clearPairing(req,res);endTeacherSession(req,res);return json(res,200,{configured:!!getDevice(req)})}
if(p==='/api/device/listen'&&req.method==='GET'){const c=getDevice(req);if(!c)fail(401,'선생님이 이 태블릿의 반을 먼저 설정해 주세요.');run('UPDATE devices SET expires=? WHERE token=?',Date.now()+DEVICE_LIFETIME,c.device_hash);deviceCookie(res,'music_device',readCookie(req,'music_device'),DEVICE_LIFETIME/1000);return json(res,200,deviceSongs(c))}

if(p==='/api/status'&&req.method==='GET')return json(res,200,{setup:!one('SELECT id FROM users LIMIT 1')&&setupAllowed(),configured:!!one('SELECT id FROM users LIMIT 1'),user:session(req)});
if(p==='/api/setup'&&req.method==='POST'){if(!setupAllowed()||one('SELECT id FROM users LIMIT 1'))fail(403,'최초 설정을 이용할 수 없습니다.');const b=await parse(req),u={id:id(),email:email(b.email),name:text(b.name,50),role:'admin'},pw=password(b.password);transaction(()=>{run('INSERT INTO users(id,email,name,password,role) VALUES(?,?,?,?,?)',u.id,u.email,u.name,pw,'admin');for(const name of ['햇살반','꽃잎반','열매반'])run('INSERT INTO classes(id,name,token) VALUES(?,?,?)',id(),name,token());});makeSession(res,u);return json(res,201,{user:u})}
if(p==='/api/login'&&req.method==='POST'){throttle(req.socket.remoteAddress);const b=await parse(req),u=one('SELECT * FROM users WHERE email=? AND active=1',email(b.email));if(!u||!matches(b.password,u.password))fail(401,'이메일 또는 비밀번호를 확인해 주세요.');makeSession(res,u);return json(res,200,{ok:true})}
if(p==='/api/logout'&&req.method==='POST'){const raw=(req.headers.cookie||'').match(/music_session=([^;]+)/)?.[1];if(raw)run('DELETE FROM sessions WHERE token=?',hash(raw));cookie(res,'',true);return json(res,200,{ok:true})}
if(p.startsWith('/api/invite/')&&req.method==='GET'){throttle('invite:'+req.socket.remoteAddress);const inv=one('SELECT email,name,expires,used FROM invitations WHERE token=?',hash(p.split('/').pop()));if(!inv||inv.used||inv.expires<Date.now())fail(410,'초대가 만료되었거나 이미 사용되었습니다. 관리자에게 다시 요청해 주세요.');return json(res,200,{email:inv.email,name:inv.name})}
if(p==='/api/accept-invite'&&req.method==='POST'){throttle('accept:'+req.socket.remoteAddress);const b=await parse(req),pw=password(b.password);const u=transaction(()=>{const inv=one('SELECT * FROM invitations WHERE token=?',hash(text(b.token,200)));if(!inv||inv.used||inv.expires<Date.now())fail(410,'초대가 만료되었거나 이미 사용되었습니다.');if(one('SELECT id FROM users WHERE email=?',inv.email))fail(409,'이미 등록된 계정입니다. 관리자에게 문의해 주세요.');const uid=id();run('INSERT INTO users(id,email,name,password,role) VALUES(?,?,?,?,?)',uid,inv.email,inv.name,pw,'teacher');for(const cid of JSON.parse(inv.class_ids))run('INSERT INTO assignments VALUES(?,?)',uid,cid);run('UPDATE invitations SET used=1 WHERE id=?',inv.id);return {id:uid}});makeSession(res,u);return json(res,201,{ok:true})}
if(p.startsWith('/api/listen/')&&req.method==='GET'){const c=one('SELECT * FROM classes WHERE token=?',p.split('/').pop());if(!c)fail(404,'우리 반 링크를 확인해 주세요.');const ids=JSON.parse(c.published),rows=q('SELECT * FROM songs WHERE archived=0'),access=`?class=${encodeURIComponent(c.token)}`;return json(res,200,{className:c.name,classId:c.id,revision:c.revision,songs:ids.map(id=>rows.find(s=>s.id===id)).filter(Boolean).map(s=>songRow(s,access))})}
if(p.startsWith('/api/media/')&&req.method==='GET'){const [, , ,sid,kind]=p.split('/'),s=one('SELECT * FROM songs WHERE id=? AND archived=0',sid);if(!s||!['audio','cover'].includes(kind))fail(404,'파일을 찾을 수 없습니다.');const ct=url.searchParams.get('class'),c=ct?one('SELECT published FROM classes WHERE token=?',ct):null;const dev=getDevice(req);if(url.searchParams.has('device')){if(!dev||!JSON.parse(dev.published).includes(sid))fail(403,'이 태블릿의 반에 공개되지 않은 음원입니다.')}else if(!session(req)&&(!c||!JSON.parse(c.published).includes(sid)))fail(403,'이 음원에 접근할 수 없습니다.');const file=kind==='audio'?s.audio_file:s.cover_file;if(!file)fail(404,'파일이 없습니다.');return stream(req,res,path.join(dataDir,'media',file),kind==='audio'?'audio/mpeg':s.cover_type)}
if(p.startsWith('/api/reset/')&&req.method==='GET'){throttle('reset:'+req.socket.remoteAddress);const r=one('SELECT u.email,u.name FROM password_resets r JOIN users u ON u.id=r.user_id WHERE r.token=? AND r.expires>? AND r.used=0 AND u.active=1',hash(p.split('/').pop()),Date.now());if(!r)fail(410,'재설정 링크가 만료되었습니다. 관리자에게 다시 요청해 주세요.');return json(res,200,r)}
if(p==='/api/reset-password'&&req.method==='POST'){throttle('reset:'+req.socket.remoteAddress);const b=await parse(req),pw=password(b.password);transaction(()=>{const r=one('SELECT r.* FROM password_resets r JOIN users u ON u.id=r.user_id WHERE r.token=? AND r.expires>? AND r.used=0 AND u.active=1',hash(text(b.token,200)),Date.now());if(!r)fail(410,'재설정 링크가 만료되었거나 이미 사용되었습니다.');run('UPDATE users SET password=? WHERE id=?',pw,r.user_id);run('DELETE FROM sessions WHERE user_id=?',r.user_id);run('UPDATE password_resets SET used=1 WHERE user_id=?',r.user_id)});cookie(res,'',true);return json(res,200,{ok:true})}
const u=requireUser(req);
if(p==='/api/library'&&req.method==='GET'){const classes=(u.role==='admin'?q('SELECT * FROM classes'):q('SELECT c.* FROM classes c JOIN assignments a ON c.id=a.class_id WHERE a.user_id=?',u.id)).map(classRow);return json(res,200,{user:u,topics:q('SELECT name FROM topics ORDER BY rowid').map(t=>t.name),songs:q('SELECT * FROM songs WHERE archived=0 ORDER BY created_at DESC').map(s=>songRow(s)),classes,collections:q('SELECT * FROM collections').filter(c=>classes.some(r=>r.id===c.class_id)).map(c=>({id:c.id,classId:c.class_id,name:c.name,items:JSON.parse(c.items)})),teachers:u.role==='admin'?q('SELECT id,email,name,role,active FROM users').map(t=>({...t,active:!!t.active,classIds:q('SELECT class_id FROM assignments WHERE user_id=?',t.id).map(a=>a.class_id)})):[],invites:u.role==='admin'?q('SELECT id,email,name,expires,used,class_ids FROM invitations WHERE used=0 AND expires>?',Date.now()).map(i=>({...i,classIds:JSON.parse(i.class_ids)})):[]})}
if(p==='/api/topics'&&req.method==='POST'){const b=await parse(req),name=text(b.name,30);run('INSERT OR IGNORE INTO topics VALUES(?)',name);return json(res,201,{name})}
if(p==='/api/songs'&&req.method==='POST'){const data=await body(req,30*1024*1024);let form;try{form=await new Request(origin+p,{method:'POST',headers:{'content-type':req.headers['content-type']},body:data}).formData()}catch{fail(400,'파일 업로드 형식을 확인해 주세요.')}const title=text(form.get('title'),70);let parsedTags;try{parsedTags=JSON.parse(form.get('tags'))}catch{fail(400,'주제를 선택해 주세요.')}const ts=tags(parsedTags),audio=form.get('audio'),image=form.get('cover');if(!audio||typeof audio==='string'||!audio.size||audio.size>25*1024*1024)fail(400,'25MB 이하의 MP3를 선택해 주세요.');const bytes=Buffer.from(await audio.arrayBuffer());if(!(bytes.subarray(0,3).toString()==='ID3'||(bytes[0]===255&&(bytes[1]&224)===224)))fail(400,'MP3 형식의 파일을 선택해 주세요.');const sid=id(),af=sid+'.mp3';let cf=null,ctype=null,cb=null;if(image&&typeof image!=='string'&&image.size){if(image.size>4*1024*1024)fail(400,'그림은 4MB 이하로 올려 주세요.');cb=Buffer.from(await image.arrayBuffer());if(cb.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))ctype='image/png';else if(cb[0]===255&&cb[1]===216&&cb[2]===255)ctype='image/jpeg';else if(cb.subarray(0,4).toString()==='RIFF'&&cb.subarray(8,12).toString()==='WEBP')ctype='image/webp';else fail(400,'PNG, JPG, WebP 그림을 선택해 주세요.');cf=sid+'.image'}try{fs.writeFileSync(path.join(dataDir,'media',af),bytes,{flag:'wx'});if(cf)fs.writeFileSync(path.join(dataDir,'media',cf),cb,{flag:'wx'});run('INSERT INTO songs(id,title,tags,audio_file,cover_file,cover_type,emoji,color,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)',sid,title,JSON.stringify(ts),af,cf,ctype,'♫','#dce8ff',u.id,Date.now())}catch(e){fs.rmSync(path.join(dataDir,'media',af),{force:true});if(cf)fs.rmSync(path.join(dataDir,'media',cf),{force:true});throw e}return json(res,201,{id:sid})}
if(/^\/api\/songs\/[^/]+$/.test(p)&&req.method==='PATCH'){const sid=p.split('/').pop(),s=one('SELECT * FROM songs WHERE id=? AND archived=0',sid);if(!s)fail(404,'곡을 찾을 수 없습니다.');if(u.role!=='admin'&&s.created_by!==u.id)fail(403,'등록한 교사 또는 관리자만 원본을 수정할 수 있습니다.');const b=await parse(req);run('UPDATE songs SET title=?,tags=? WHERE id=?',text(b.title,70),JSON.stringify(tags(b.tags)),sid);return json(res,200,{ok:true})}
if(/^\/api\/classes\/[^/]+\/(draft|publish|rotate)$/.test(p)&&req.method==='POST'){const cid=p.split('/')[3],action=p.split('/')[4];canClass(u,cid);const b=await parse(req);transaction(()=>{const c=one('SELECT * FROM classes WHERE id=?',cid);if(action==='rotate'){if(u.role!=='admin')fail(403,'관리자만 링크를 재발급할 수 있습니다.');run('UPDATE classes SET token=?,revision=revision+1 WHERE id=?',token(),cid);return}if(b.revision!==c.revision)fail(409,'다른 선생님이 목록을 변경했습니다. 새로고침한 뒤 다시 선택해 주세요.');const items=songIds(b.items);if(action==='draft')run('UPDATE classes SET draft=?,revision=revision+1 WHERE id=?',JSON.stringify(items),cid);else run('UPDATE classes SET draft=?,published=?,revision=revision+1 WHERE id=?',JSON.stringify(items),JSON.stringify(items),cid)});return json(res,200,{ok:true})}
if(p==='/api/collections'&&req.method==='POST'){const b=await parse(req);canClass(u,b.classId);run('INSERT INTO collections VALUES(?,?,?,?)',id(),b.classId,text(b.name,50),JSON.stringify(songIds(b.items)));return json(res,201,{ok:true})}
if(/^\/api\/classes\/[^/]+$/.test(p)&&req.method==='PATCH'){admin(req);const cid=p.split('/').pop();canClass(u,cid);const b=await parse(req);run('UPDATE classes SET name=?,revision=revision+1 WHERE id=?',text(b.name,30),cid);return json(res,200,{ok:true})}
if(/^\/api\/teachers\/[^/]+\/reset$/.test(p)&&req.method==='POST'){admin(req);const uid=p.split('/')[3],target=one('SELECT id FROM users WHERE id=? AND active=1',uid);if(!target)fail(404,'이용 중인 교사를 찾을 수 없습니다.');const raw=token();transaction(()=>{run('UPDATE password_resets SET used=1 WHERE user_id=?',uid);run('INSERT INTO password_resets VALUES(?,?,?,0)',hash(raw),uid,Date.now()+3600000)});return json(res,201,{url:origin+'/reset#'+raw})}
if(p==='/api/classes'&&req.method==='POST'){admin(req);const b=await parse(req);run('INSERT INTO classes(id,name,token) VALUES(?,?,?)',id(),text(b.name,30),token());return json(res,201,{ok:true})}
if(p==='/api/invitations'&&req.method==='POST'){admin(req);const b=await parse(req),em=email(b.email),name=text(b.name,50);if(one('SELECT id FROM users WHERE email=?',em))fail(409,'이미 등록된 이메일입니다.');if(!Array.isArray(b.classIds)||!b.classIds.length)fail(400,'담당 반을 선택해 주세요.');for(const cid of b.classIds)canClass(u,cid);const raw=token();transaction(()=>{run('UPDATE invitations SET used=1 WHERE email=? AND used=0',em);run('INSERT INTO invitations VALUES(?,?,?,?,?,?,0)',id(),em,name,hash(raw),JSON.stringify([...new Set(b.classIds)]),Date.now()+7*86400000)});return json(res,201,{url:`${origin}/invite#${raw}`,delivery:'copy-link'})}
if(/^\/api\/teachers\/[^/]+$/.test(p)&&req.method==='PATCH'){admin(req);const uid=p.split('/').pop(),t=one('SELECT * FROM users WHERE id=?',uid),b=await parse(req);if(!t)fail(404,'교사를 찾을 수 없습니다.');if(t.role==='admin')fail(400,'관리자 계정은 이 화면에서 변경할 수 없습니다.');if(!Array.isArray(b.classIds))fail(400,'담당 반을 선택해 주세요.');for(const cid of b.classIds)canClass(u,cid);transaction(()=>{run('UPDATE users SET active=? WHERE id=?',b.active?1:0,uid);run('DELETE FROM assignments WHERE user_id=?',uid);for(const cid of new Set(b.classIds))run('INSERT INTO assignments VALUES(?,?)',uid,cid);if(!b.active)run('DELETE FROM sessions WHERE user_id=?',uid)});return json(res,200,{ok:true})}
fail(404,'요청을 찾을 수 없습니다.');
}
function stream(req,res,file,type){if(!fs.existsSync(file))fail(404,'파일을 찾을 수 없습니다.');const size=fs.statSync(file).size;let start=0,end=size-1,status=200;if(req.headers.range){const m=/^bytes=(\d*)-(\d*)$/.exec(req.headers.range);if(!m||(!m[1]&&!m[2])){res.writeHead(416,{'Content-Range':`bytes */${size}`});return res.end()}start=m[1]?Number(m[1]):Math.max(0,size-Number(m[2]));end=m[1]&&m[2]?Math.min(Number(m[2]),size-1):size-1;if(start>end||start>=size){res.writeHead(416,{'Content-Range':`bytes */${size}`});return res.end()}status=206;res.setHeader('Content-Range',`bytes ${start}-${end}/${size}`)}res.writeHead(status,{'Content-Type':type,'Content-Length':end-start+1,'Accept-Ranges':'bytes','Cache-Control':'private, no-store'});fs.createReadStream(file,{start,end}).pipe(res)}
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Frame-Options','DENY');res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; media-src 'self' blob:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");try{const url=new URL(req.url,origin);if(url.pathname.startsWith('/api/'))return await api(req,res,url);if(req.method!=='GET')fail(405,'지원하지 않는 요청입니다.');let route=decodeURIComponent(url.pathname);let filename=['/','/teacher','/admin','/invite','/reset','/demo','/listen','/demo/tablet'].includes(route)||/^\/listen\/[^/]+$/.test(route)?'index.html':route.slice(1);const file=path.resolve(root,'public',filename);if(!file.startsWith(path.join(root,'public')+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile())fail(404,'페이지를 찾을 수 없습니다.');res.writeHead(200,{'Content-Type':({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png'})[path.extname(file)]||'application/octet-stream','Cache-Control':'no-cache'});fs.createReadStream(file).pipe(res)}catch(e){if(res.headersSent){res.destroy();return}const status=e.status||(e.code?.startsWith('ERR_SQLITE')?409:500);if(status===500)console.error('Request failed:',e.message);json(res,status,{error:e.status?e.message:status===409?'이미 등록된 항목이거나 저장 중 충돌이 발생했습니다.':'저장에 실패했습니다. 잠시 후 다시 시도해 주세요.'})}});
server.listen(port,host,()=>console.log(`Music library ready: ${origin}`));
function shutdown(){server.close(()=>{db.close();process.exit(0)})}process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
