import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {mkdtemp,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {DatabaseSync} from 'node:sqlite';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
test('common link: scoped pairing, persistent device, logout, safe reconfiguration and revocation',async()=>{
const dir=await mkdtemp(path.join(os.tmpdir(),'saessak-device-test-')),base='http://127.0.0.1:14318';let proc;
async function start(){proc=spawn(process.execPath,['server.mjs'],{cwd:root,env:{...process.env,HOST:'127.0.0.1',PORT:'14318',APP_ORIGIN:base,DATA_DIR:dir,NODE_ENV:'test'},stdio:['ignore','pipe','pipe']});await new Promise((resolve,reject)=>{proc.stdout.once('data',resolve);proc.once('error',reject);proc.once('exit',code=>reject(Error('Server exit '+code)))})}
async function stop(){if(!proc||proc.exitCode!==null)return;await new Promise(r=>{proc.once('exit',r);proc.kill()})}
const staff={},tablet={};
async function call(p,{jar={},method='GET',body,origin=base,headers={}}={}){const hs={Origin:origin,...headers};const cookie=Object.entries(jar).map(([k,v])=>k+'='+v).join('; ');if(cookie)hs.Cookie=cookie;let payload=body;if(body&&!(body instanceof FormData)){hs['Content-Type']='application/json';payload=JSON.stringify(body)}const res=await fetch(base+p,{method,headers:hs,body:payload});for(const c of res.headers.getSetCookie()){const pair=c.split(';')[0],i=pair.indexOf('='),name=pair.slice(0,i),value=pair.slice(i+1);if(value)jar[name]=value;else delete jar[name]}let result;try{result=await res.json()}catch{}return {status:res.status,data:result,headers:res.headers}}
try{await start();assert.equal((await call('/listen')).status,200);assert.equal((await call('/api/device/listen')).status,401);assert.equal((await call('/api/device/enroll',{method:'POST',body:{classId:'bad'}})).status,401);
await call('/api/setup',{jar:staff,method:'POST',body:{name:'Admin Test',email:'admin@example.test',password:'test-password-12345'}});let lib=(await call('/api/library',{jar:staff})).data;const [a,b]=lib.classes;
async function addSong(title){const form=new FormData();form.set('title',title);form.set('tags','["봄"]');form.set('audio',new Blob([Buffer.concat([Buffer.from('ID3'),Buffer.alloc(50)])],{type:'audio/mpeg'}),'test.mp3');return (await call('/api/songs',{jar:staff,method:'POST',body:form})).data.id}
const sa=await addSong('A song'),sb=await addSong('B song');for(const [c,s]of [[a,sa],[b,sb]])assert.equal((await call('/api/classes/'+c.id+'/publish',{jar:staff,method:'POST',body:{items:[s],revision:0}})).status,200);
const inv=(await call('/api/invitations',{jar:staff,method:'POST',body:{email:'teacher@example.test',name:'Teacher Test',classIds:[a.id]}})).data;
await call('/api/accept-invite',{jar:tablet,method:'POST',body:{token:inv.url.split('#')[1],password:'teacher-password-123'}});const oldTeacher={...tablet};
assert.equal((await call('/api/device/enroll',{jar:tablet,method:'POST',body:{classId:a.id}})).status,401);
const entered=await call('/api/device/enter',{jar:tablet,method:'POST',body:{}});assert.equal(entered.data.configured,false);assert.equal((await call('/api/library',{jar:oldTeacher})).status,401);
assert.equal((await call('/api/device/auth',{jar:tablet,method:'POST',origin:'https://wrong.example',body:{}})).status,403);
const verified=await call('/api/device/auth',{jar:tablet,method:'POST',body:{email:'teacher@example.test',password:'teacher-password-123'}});assert.equal(verified.status,200);assert.deepEqual(verified.data.classes.map(c=>c.id),[a.id]);assert.ok(tablet.music_pairing);assert.equal(tablet.music_session,undefined);assert.ok(verified.headers.getSetCookie().find(c=>c.startsWith('music_pairing=')&&c.includes('HttpOnly')&&c.includes('Max-Age=600')));
assert.equal((await call('/api/library',{jar:tablet})).status,401);assert.equal((await call('/api/device/enroll',{jar:tablet,method:'POST',body:{classId:b.id}})).status,403);
const enroll=await call('/api/device/enroll',{jar:tablet,method:'POST',body:{classId:a.id}});assert.equal(enroll.status,201);assert.ok(tablet.music_device);assert.equal(tablet.music_pairing,undefined);assert.equal((await call('/api/status',{jar:tablet})).data.user,null);assert.equal((await call('/api/library',{jar:tablet})).status,401);
const listen=(await call('/api/device/listen',{jar:tablet})).data;assert.equal(listen.classId,a.id);assert.deepEqual(listen.songs.map(s=>s.id),[sa]);assert.ok(listen.songs[0].audio.endsWith('?device=1'));assert.equal((await call('/api/media/'+sa+'/audio?device=1',{jar:tablet,headers:{Range:'bytes=0-9'}})).status,206);assert.equal((await call('/api/media/'+sb+'/audio?device=1&class='+b.token,{jar:tablet})).status,403);
assert.equal((await call('/api/device/enroll',{jar:tablet,method:'POST',body:{classId:b.id}})).status,401);
await stop();await start();assert.equal((await call('/api/device/listen',{jar:tablet})).data.classId,a.id);
const teacherId=(await call('/api/library',{jar:staff})).data.teachers.find(t=>t.role==='teacher').id;
await call('/api/teachers/'+teacherId,{jar:staff,method:'PATCH',body:{active:true,classIds:[b.id]}});
const changed=await call('/api/device/auth',{jar:tablet,method:'POST',body:{email:'teacher@example.test',password:'teacher-password-123'}});assert.deepEqual(changed.data.classes.map(c=>c.id),[b.id]);assert.equal((await call('/api/device/enroll',{jar:tablet,method:'POST',body:{classId:a.id}})).status,403);assert.equal((await call('/api/device/listen',{jar:tablet})).data.classId,a.id);
const oldDevice={music_device:tablet.music_device},stalePair={music_pairing:tablet.music_pairing};await call('/api/device/enroll',{jar:tablet,method:'POST',body:{classId:b.id}});assert.equal((await call('/api/device/listen',{jar:tablet})).data.classId,b.id);assert.equal((await call('/api/device/listen',{jar:oldDevice})).status,401);assert.equal((await call('/api/device/enroll',{jar:stalePair,method:'POST',body:{classId:b.id}})).status,401);assert.equal((await call('/api/media/'+sa+'/audio?device=1',{jar:tablet})).status,403);
await call('/api/device/auth',{jar:tablet,method:'POST',body:{email:'teacher@example.test',password:'teacher-password-123'}});const db=new DatabaseSync(path.join(dir,'library.sqlite'));db.exec('UPDATE device_pairings SET expires=0');db.close();assert.equal((await call('/api/device/enroll',{jar:tablet,method:'POST',body:{classId:b.id}})).status,401);assert.equal((await call('/api/device/cancel',{jar:tablet,method:'POST',body:{}})).data.configured,true);assert.equal((await call('/api/device/listen',{jar:tablet})).data.classId,b.id);
}finally{await stop();assert.ok(path.resolve(dir).startsWith(path.resolve(os.tmpdir())+path.sep+'saessak-device-test-'));await rm(dir,{recursive:true,force:true})}
});
